# Copyright (c) 2026 Daan Vervacke
# SPDX-License-Identifier: MIT
"""Unofficial asynchronous Python library to interact with the ENGIE Belgium API."""

from importlib.metadata import PackageNotFoundError, version

from ._auth import AuthFlow
from .client import EngieBeClient
from .const import (
    DEFAULT_CLIENT_ID,
    EpexGranularity,
    FeatureFlagKey,
    MfaMethod,
    SolarInferenceKey,
    SolarSurplusLevel,
    TouSlotCode,
    UsageGranularity,
)
from .exceptions import (
    EngieBeAuthenticationError,
    EngieBeCommunicationError,
    EngieBeEpexNotPublishedError,
    EngieBeError,
    EngieBeInvalidResponseError,
    EngieBeMfaError,
)
from .models import (
    AccountBalance,
    AccountRelation,
    BillingDetails,
    BillingOverview,
    BusinessAgreement,
    ConsumptionAddress,
    ContractInfo,
    CustomerAccount,
    CustomerAccountRelations,
    EanPrices,
    ElectricityUsage,
    EnergyContract,
    EnergyContractsResponse,
    EnergyCostPair,
    EpexPayload,
    EpexSlot,
    FeatureFlag,
    FinancialTransaction,
    GasUsage,
    HappyHourComparison,
    HappyHourEvent,
    HappyHourMonthData,
    HappyHourMonthReport,
    HappyHourWindow,
    MeteringConfiguration,
    MonthlyPeaks,
    MonthReportHistoryEntry,
    Peak,
    PricePeriod,
    PriceSlot,
    PricesResponse,
    ProductConfiguration,
    ServicePoint,
    ServicePointInstallation,
    ServicePointMarketDetails,
    SimulatedCost,
    SimulatedCostFlow,
    SimulatedEnergy,
    SimulatedEnergyFlow,
    SolarSurplusDay,
    SolarSurplusForecasts,
    SolarSurplusSlot,
    TouDirectionSchedule,
    TouGridMeterSchedule,
    TouSchedule,
    TouScheduleItem,
    TouSchedulesResponse,
    TouSlot,
    UsageDetailsResponse,
    UsageDirectionBreakdown,
    UsageElectricityBreakdown,
    UsageItem,
    UsageTouCrossPart,
    UsageTouPart,
    bare_ean,
    ean_with_delivery_point_suffix,
)

try:
    __version__ = version("aioengiebelgium")
except PackageNotFoundError:  # pragma: no cover
    __version__ = "0.0.0"

__all__ = [
    "DEFAULT_CLIENT_ID",
    "AccountBalance",
    "AccountRelation",
    "AuthFlow",
    "BillingDetails",
    "BillingOverview",
    "BusinessAgreement",
    "ConsumptionAddress",
    "ContractInfo",
    "CustomerAccount",
    "CustomerAccountRelations",
    "EanPrices",
    "ElectricityUsage",
    "EnergyContract",
    "EnergyContractsResponse",
    "EnergyCostPair",
    "EngieBeAuthenticationError",
    "EngieBeClient",
    "EngieBeCommunicationError",
    "EngieBeEpexNotPublishedError",
    "EngieBeError",
    "EngieBeInvalidResponseError",
    "EngieBeMfaError",
    "EpexGranularity",
    "EpexPayload",
    "EpexSlot",
    "FeatureFlag",
    "FeatureFlagKey",
    "FinancialTransaction",
    "GasUsage",
    "HappyHourComparison",
    "HappyHourEvent",
    "HappyHourMonthData",
    "HappyHourMonthReport",
    "HappyHourWindow",
    "MeteringConfiguration",
    "MfaMethod",
    "MonthReportHistoryEntry",
    "MonthlyPeaks",
    "Peak",
    "PricePeriod",
    "PriceSlot",
    "PricesResponse",
    "ProductConfiguration",
    "ServicePoint",
    "ServicePointInstallation",
    "ServicePointMarketDetails",
    "SimulatedCost",
    "SimulatedCostFlow",
    "SimulatedEnergy",
    "SimulatedEnergyFlow",
    "SolarInferenceKey",
    "SolarSurplusDay",
    "SolarSurplusForecasts",
    "SolarSurplusLevel",
    "SolarSurplusSlot",
    "TouDirectionSchedule",
    "TouGridMeterSchedule",
    "TouSchedule",
    "TouScheduleItem",
    "TouSchedulesResponse",
    "TouSlot",
    "TouSlotCode",
    "UsageDetailsResponse",
    "UsageDirectionBreakdown",
    "UsageElectricityBreakdown",
    "UsageGranularity",
    "UsageItem",
    "UsageTouCrossPart",
    "UsageTouPart",
    "__version__",
    "bare_ean",
    "ean_with_delivery_point_suffix",
]
